/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/witch/model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature_druide" scale={1.908}>
          <primitive object={nodes.root} />
          <skinnedMesh name="druid" geometry={nodes.druid.geometry} material={materials.color_main} skeleton={nodes.druid.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
