export const khodamList = [
    'Macan Biskuat',
    'Rawa Rontek',
    'Ular Sawah',
    'Macan Putih',
    'Tahu Bulat',
    'Tuyul Mullet',
    'Kambing Amazon',
    'Singa Dangdut',
    'Lalat Sumbing',
    'Cicak Sumbing',
    'Kecap Bango',
    'Belut Sawah',
    'Undur-Undur',
    'Kuntilanak Botak',
    'Pocong Sumbing',
    'Pocong Mullet',
    'Kura-Kura Ninja',
    'Macan Tutul',
    'Ular Kadut',
    'Ikan Cupang',
    'Kadal Mesir',
    'Ulat Teh Pucuk',
    'Pinguin Pino',
    'Nyamuk Sumbing',
    'Siluman Kadal',
    'Cacing Kremi',
    'Kelinci Pincang',
    'Hiu Salto',
    'Naga Bonar',
    'Jam Dinding',
    'Hello Kitty',
    'Doraemon',
    'Boboiboy',
    'Adudu',
    'Gopal',
    'Tuan Krab',
    'Patrick',
    'Kupu-Kupu',
    'Pocong Atletik',
    'Harimau Sumbing',
    'Sayur Lodeh',
    'Semur Jengkol'
]